# -*- coding: utf-8 -*-
"""파이썬 챌린지반.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AePqiiSNyd4DKONmEdze48dOhBsKl7PV
"""

import requests
import pandas as pd
from google.colab import userdata
API_KEY = userdata.get("lostark_api")
ITEM_ID = '65203905'
url = f'https://developer-lostark.game.onstove.com/markets/items/{ITEM_ID}'

headers = {
    'Authorization': f'bearer {API_KEY}' ,
    'accept': 'application/json'
}
response = requests.get(url, headers=headers)
data = response.json()

all_stats = []
for item in data:
    for stat in item["Stats"]:
        stat["Name"] = item["Name"]
        all_stats.append(stat)

df = pd.DataFrame(all_stats)
df = df[df['AvgPrice'] != 0]
df = df.reset_index()
df = df.drop(columns=['index'])
df
# API_KEY

import requests
import pandas as pd

# API 요청 (이미 요청된 것으로 가정)
# response = requests.get(url, headers=headers)  # 실제 API 요청
data = response.json()  # API 응답 데이터를 JSON 형식으로 변환

# 각 항목의 'Stats' 배열 데이터를 추출하여 데이터프레임으로 변환
all_stats = []
for item in data:
    for stat in item["Stats"]:
        stat["Name"] = item["Name"]
        all_stats.append(stat)

# 데이터프레임 생성
df = pd.DataFrame(all_stats)

# 데이터프레임 출력
print(df)